# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ea9dd2ab25d3ae9431ac623f718401f5218eaa423ea098011f089182839f1e7039473236c55223f35dffd5001c4a093b7d537e46d17184d34ac42a4ca2d5610

test:
  secret_key_base: 3ce099d79b6209d915d4518b373809fe1bfab0a1d3715cbf4a8c93e9c90fee431fd77f5b40d034ff8a7b2b9b8b148ac8e396596187d5024096f3b82851e24888

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
